kind: Service
apiVersion: v1
metadata:
  name: nginx-test-service
  labels:
    app: nginx
    role: %TARGET_ROLE%
    env: test
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: %TARGET_ROLE%
  ports:
    - port: 80
      targetPort: 80
